engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  pep8:
    enabled: true

ratings:
  paths:
  - "**.py"

exclude_paths:
- test/